### PR TITLE
files-np: Add version 2.4.21

### PR DESCRIPTION
**Pull request by Zliced13**
Closes https://github.com/ScoopInstaller/Extras/issues/9279

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rasa** [comment]
```batch
--> Installing the Manifest files-np.json

Installing 'files-np' (2.4.21) [64bit]
Files.Package_2.4.21.0_x64_arm64_Sideload.msixbundle (202.4 MB) [=================================================] 100%
Checking hash of Files.Package_2.4.21.0_x64_arm64_Sideload.msixbundle ... ok.
Running pre_install script...
Linking ~\scoop\apps\files-np\current => ~\scoop\apps\files-np\2.4.21
'files-np' (2.4.21) was installed successfully!

--> Refreshing environment variables

--> Comparing ARP Entries

PS C:\Users\WDAGUtilityAccount\Desktop\bucket> scoop uninstall files-np
Uninstalling 'files-np' (2.4.21).
Running pre_uninstall script...
Remove-Item : Cannot find path 'C:\ProgramData\Packages' because it does not exist.
At line:2 char:1
+ Remove-Item "$env:ProgramData\Packages\Files_*" -Force -Recurse
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\ProgramData\Packages:String) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Unlinking ~\scoop\apps\files-np\current
'files-np' was uninstalled.
PS C:\Users\WDAGUtilityAccount\Desktop\bucket>
```

**Comment by rasa** [comment]
@Zliced13 Uninstall fails. See above.

**Comment by Zliced13** [comment]
@rasa Test it again, it should work this time.

**Comment by rasa** [comment]
``batch
--> Running: scoop install  files-np.json

Installing 'files-np' (2.4.21) [64bit]
Loading Files.Package_2.4.21.0_x64_arm64_Sideload.msixbundle from cache
Checking hash of Files.Package_2.4.21.0_x64_arm64_Sideload.msixbundle ... ok.
Running pre_install script...
Linking ~\scoop\apps\files-np\current => ~\scoop\apps\files-np\2.4.21
'files-np' (2.4.21) was installed successfully!

--> Refreshing environment variables

--> Comparing ARP entries

PS C:\Users\WDAGUtilityAccount\Desktop\bucket> scoop uninstall files-np
Uninstalling 'files-np' (2.4.21).
Running pre_uninstall script...
Unlinking ~\scoop\apps\files-np\current
'files-np' was uninstalled.
PS C:\Users\WDAGUtilityAccount\Desktop\bucket>
```

**Pull request merged**
