### PR TITLE
dshidmini-np: Add version 2.2.282.0

### PR DESCRIPTION
**Pull request by sitiom**
Virtual HID Mini-user-mode-driver for Sony DualShock 3 Controllers

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by issaclin32** [comment]
I think we can just add **admin rights check**, instead of forcing the app to be installed globally.

For instance, add this in the first line of `installer` and `uninstaller` scripts:
```
"if (!(is_admin)) { error \"$app requires admin rights to $cmd\"; break }",
```
$cmd will be shown as `install`, `uninstall`, `update`, ... depending on what the command is.

By the way, we should use `break` instead of `exit`.
If the user is installing / upgrading multiple apps. `exit` would cause the whole process to stop, while `break` only skips the installation of this app.

**Comment by sitiom** [comment]
> I think we can just add **admin rights check**, instead of forcing the app to be installed globally.

It's a driver install, which is a system-wide install. That is why I am limiting it to be installed globally. It doesn't make sense to have it in the user scope.

> By the way, we should use `break` instead of `exit`. If the user is installing / upgrading multiple apps. `exit` would cause the whole process to stop, while `break` only skips the installation of this app.

Can `return` also do the job?

**Comment by issaclin32** [comment]
> Can `return` also do the job?

`return` will only stop the current script block. **i.e.** `pre_install`, `installer.script`, `pre_uninstall`, ...

**Comment by issaclin32** [comment]
> It's a driver install, which is a system-wide install. That is why I am limiting it to be installed globally. It doesn't make sense to have it in the user scope.

Okay. I see.

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
