### PR TITLE
open-shell-np: Add version 4.4.170

### PR DESCRIPTION
**Pull request by Zliced13**
Relates to https://github.com/ScoopInstaller/Extras/issues/5100

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rasa** [comment]
@Zliced13 It's hanging in the pre_uninstall. I see `msiexec.exe /V` running,

**Comment by Zliced13** [comment]
@rasa Fixed, try it now to see if it works.

**Comment by rasa** [comment]
@Zliced13 It's still hanging on uninstall, even after I manually kill the `msiexec.exe /V` process:
```batch
--> Running: scoop install  open-shell-np.json

Installing 'open-shell-np' (4.4.170) [64bit]
Loading OpenShellSetup_4_4_170.exe from cache
Checking hash of OpenShellSetup_4_4_170.exe ... ok.
Running pre_install script...
Running installer script...
Replacing Start Menu with Open Shell, please wait and don't cancel the script...
Done!
Linking ~\scoop\apps\open-shell-np\current => ~\scoop\apps\open-shell-np\4.4.170
'open-shell-np' (4.4.170) was installed successfully!

--> Refreshing environment variables

--> Comparing ARP entries

DisplayName DisplayVersion Publisher           ProductCode
----------- -------------- ---------           -----------
Open-Shell  4.4.170        The Open-Shell Team {F07C0CF2-6021-403A-99CA-1164340B09FB}



PS C:\Users\WDAGUtilityAccount\Desktop\bucket> scoop uninstall open-shell-np
Uninstalling 'open-shell-np' (4.4.170).
Running pre_uninstall script...
Restoring previous Start Menu, please wait and don't cancel the script...
```

**Comment by Zliced13** [comment]
@rasa It worked fine for my VM, how come it doesn't work for yours?

**Comment by rasa** [comment]
> @rasa It worked fine for my VM, how come it doesn't work for yours?

I don't know. My Sandbox is Windows 10 based. Are you Windows 11?

Perhaps something like this would be more stable (with comments):

```powershell
        "Start-Process 'msiexec' -Verb 'RunAs' -ArgumentList @('/x', \"$dir\\setup.msi\", '/qn')", # removed -Wait
        "while (Test-Path \"$env:ProgramFiles\\Open-Shell\") { Start-Sleep -Milliseconds 5500 }", # but maybe exit after 60 seconds or so?
        "Start-Process 'taskkill' -Wait -Verb 'RunAs' -WindowStyle 'Hidden' -ArgumentList ('/F', '/IM', 'explorer.exe')", # maybe remove wait, and wait for the process to die?
        "Start-Process 'explorer.exe' -Verb 'RunAs' -WindowStyle 'Hidden'" # why -Wait here?
```

**Comment by Zliced13** [comment]
I'm using Windows 10 on my VM.

**Comment by rasa** [comment]
```batch
PS C:\Users\WDAGUtilityAccount\Desktop\bucket> scoop install .\open-shell-np.json
Installing 'open-shell-np' (4.4.170) [64bit]
Loading OpenShellSetup_4_4_170.exe from cache
Checking hash of OpenShellSetup_4_4_170.exe ... ok.
Running pre_install script...
Running installer script...
Replacing Start Menu with Open Shell, please wait and don't cancel the script...
Done!
Linking ~\scoop\apps\open-shell-np\current => ~\scoop\apps\open-shell-np\4.4.170
'open-shell-np' (4.4.170) was installed successfully!
PS C:\Users\WDAGUtilityAccount\Desktop\bucket> scoop uninstall open-shell-np
Uninstalling 'open-shell-np' (4.4.170).
Running pre_uninstall script...
Restoring previous Start Menu, please wait and don't cancel the script...
Previous Start Menu Restored!
Unlinking ~\scoop\apps\open-shell-np\current
'open-shell-np' was uninstalled.
PS C:\Users\WDAGUtilityAccount\Desktop\bucket>
```

**Pull request merged**
