### PR TITLE
grammarly-np: Add version 1.0.23.347

### PR DESCRIPTION
**Pull request by Zliced13**
Closes https://github.com/ScoopInstaller/Extras/issues/7126

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Zliced13** [comment]
@issaclin32 I created a working checkver for Grammarly, this should solve your `checkver` problem.

**Comment by rasa** [comment]
@Zliced13 Never finishes installing:
```batch
--> Installing the Manifest grammarly-np.json

Installing 'grammarly-np' (1.0.23.347) [64bit]
GrammarlyInstaller.exe (14.0 MB) [================================================================================] 100%
Checking hash of GrammarlyInstaller.exe ... ok.
Running pre_install script...
Linking ~\scoop\apps\grammarly-np\current => ~\scoop\apps\grammarly-np\1.0.23.347
'grammarly-np' (1.0.23.347) was installed successfully!

--> Refreshing environment variables

--> Comparing ARP Entries

DisplayName           DisplayVersion Publisher ProductCode
-----------           -------------- --------- -----------
Grammarly for Windows 1.0.23.347               Grammarly Desktop Integrations



PS C:\Users\WDAGUtilityAccount\Desktop\bucket> scoop uninstall grammarly-np
Uninstalling 'grammarly-np' (1.0.23.347).
Running pre_uninstall script...
```
2023-01-19_18-28-26-WindowsSandboxClient-Windows_Sandbox

**Comment by rasa** [comment]
Works!
```batch
--> Installing the Manifest grammarly-np.json

Installing 'grammarly-np' (1.0.23.347) [64bit]
GrammarlyInstaller.exe (14.0 MB) [================================================================================] 100%
Checking hash of GrammarlyInstaller.exe ... ok.
Running pre_install script...
Linking ~\scoop\apps\grammarly-np\current => ~\scoop\apps\grammarly-np\1.0.23.347
'grammarly-np' (1.0.23.347) was installed successfully!

--> Refreshing environment variables

--> Comparing ARP Entries

DisplayName           DisplayVersion Publisher ProductCode
-----------           -------------- --------- -----------
Grammarly for Windows 1.0.23.347               Grammarly Desktop Integrations



PS C:\Users\WDAGUtilityAccount\Desktop\bucket> scoop uninstall grammarly-np
Uninstalling 'grammarly-np' (1.0.23.347).
Running pre_uninstall script...
Unlinking ~\scoop\apps\grammarly-np\current
'grammarly-np' was uninstalled.
PS C:\Users\WDAGUtilityAccount\Desktop\bucket>
```

**Pull request merged**
