### PR TITLE
vmware-horizon-client-np@2209-8.7.0-20649873: Update to latest version and fix checkver

### PR DESCRIPTION
**Pull request by beargle**
[VMware Horizon Client for Windows 2209 Release Notes](https://docs.vmware.com/en/VMware-Horizon-Client-for-Windows/2209/rn/vmware-horizon-client-for-windows-2209-release-notes/index.html#whatsnew)

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rasa** [comment]
```batch
--> Installing the Manifest vmware-horizon-client-np.json

Installing 'dark' (3.11.2) [64bit] from main bucket
dark-3.11.2.zip (3.5 MB) [========================================================================================] 100%
Checking hash of dark-3.11.2.zip ... ok.
Extracting dark-3.11.2.zip ... done.
Linking ~\scoop\apps\dark\current => ~\scoop\apps\dark\3.11.2
Creating shim for 'dark'.
'dark' (3.11.2) was installed successfully!
Installing 'vmware-horizon-client-np' (2209-8.7.0-20649873) [64bit]
The remote server returned an error: (404) Not Found.
URL https://download3.vmware.com/software/view/viewclients/CART23FQ3/VMware-Horizon-Client-2209-8.7.0-20649873.exe#/VMware-Horizon-Client-Setup.exe is not valid

--> Refreshing environment variables

--> Comparing ARP Entries

PS C:\Users\WDAGUtilityAccount\Desktop\bucket> scoop install .\vmware-horizon-client-np.json
WARN  Purging previous failed installation of vmware-horizon-client-np.
ERROR 'vmware-horizon-client-np' isn't installed correctly.
Removing older version (2209-8.7.0-20649873).
'vmware-horizon-client-np' was uninstalled.
Installing 'vmware-horizon-client-np' (2209-8.7.0-20649873) [64bit]
The remote server returned an error: (404) Not Found.
URL https://download3.vmware.com/software/view/viewclients/CART23FQ3/VMware-Horizon-Client-2209-8.7.0-20649873.exe#/VMware-Horizon-Client-Setup.exe is not valid
PS C:\Users\WDAGUtilityAccount\Desktop\bucket>
```

**Comment by rasa** [comment]
Looks good, i will test soon.

**Comment by rasa** [comment]
@Zliced13 Getting a 404:
```batch
--> Running: scoop install  vmware-horizon-client-np.json

Installing 'vmware-horizon-client-np' (2209-8.7.0-20649873) [64bit]
The remote server returned an error: (404) Not Found.
URL https://download3.vmware.com/software/CART23FQ3/VMware-Horizon-Client-2209-8.7.0-20649873.exe#/VMware-Horizon-Client-Setup.exe is not valid

--> Refreshing environment variables

--> Comparing ARP entries

PS C:\Users\WDAGUtilityAccount\Desktop\bucket>
```

**Comment by beargle** [comment]
> @beargle Getting a 404:
> 
> ```batchfile
> --> Running: scoop install  vmware-horizon-client-np.json
> 
> Installing 'vmware-horizon-client-np' (2209-8.7.0-20649873) [64bit]
> The remote server returned an error: (404) Not Found.
> URL https://download3.vmware.com/software/CART23FQ3/VMware-Horizon-Client-2209-8.7.0-20649873.exe#/VMware-Horizon-Client-Setup.exe is not valid
> 
> --> Refreshing environment variables
> 
> --> Comparing ARP entries
> 
> PS C:\Users\WDAGUtilityAccount\Desktop\bucket>
> ```
This URL works: https://download3.vmware.com/software/CART23FQ3_WIN_2209/VMware-Horizon-Client-2209-8.7.0-20649873.exe

This does not: https://download3.vmware.com/software/CART23FQ3/VMware-Horizon-Client-2209-8.7.0-20649873.exe 

Revert of https://github.com/ScoopInstaller/Nonportable/pull/114/commits/0e29587839de6051572aa86b2d1fea2ae49908c6 should resolve.

**Comment by beargle** [comment]
Will verify the autoupdate URL is working as expected.

**Comment by beargle** [comment]
Could only find an autoupdate url available which changes between versions, e.g.

https://customerconnect.vmware.com/channel/public/api/v1.0/dlg/details?downloadGroup=CART21FQ4_WIN_2012&productId=1027

https://customerconnect.vmware.com/channel/public/api/v1.0/dlg/details?downloadGroup=CART23FQ3_WIN_2209&productId=1027

No great solution here. [This is an example of how chocolatey handles it](https://github.com/virtualex-itv/chocolatey-packages/blob/4dbc647747aeb08da32cb519364100943f8a4cf2/automatic/vmware-horizon-client/update.ps1#L13-L18), but we do not have that multi-step autoupdate ability with scoop.

Not sure what the test cases are, but checkurls, checkver, and install works in current state.

**Comment by rasa** [comment]
All's well now. Even checkver doesn't update the URL.
```batch
--> Running: scoop install  vmware-horizon-client-np.json

Installing 'vmware-horizon-client-np' (2209-8.7.0-20649873) [64bit]
VMware-Horizon-Client-2209-8.7.0-20649873.exe (416.4 MB) [========================================================] 100%
Checking hash of VMware-Horizon-Client-2209-8.7.0-20649873.exe ... ok.
Running installer script...
Linking ~\scoop\apps\vmware-horizon-client-np\current => ~\scoop\apps\vmware-horizon-client-np\2209-8.7.0-20649873
Creating shim for 'vmware-view'.
Creating shortcut for VMware Horizon Client (vmware-view.exe)
'vmware-horizon-client-np' (2209-8.7.0-20649873) was installed successfully!

--> Refreshing environment variables

--> Comparing ARP entries

PS C:\Users\WDAGUtilityAccount\Desktop\bucket> scoop uninstall vmware-horizon-client-np
Uninstalling 'vmware-horizon-client-np' (2209-8.7.0-20649873).
Removing shim 'vmware-view.shim'.
Removing shim 'vmware-view.exe'.
Removing shortcut ~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\VMware Horizon Client.lnk
Unlinking ~\scoop\apps\vmware-horizon-client-np\current
'vmware-horizon-client-np' was uninstalled.
PS C:\Users\WDAGUtilityAccount\Desktop\bucket>
```

**Pull request merged**
