### PR TITLE
devtoys-np: Add version 1.0.10.0

### PR DESCRIPTION
**Pull request by Zliced13**
Closes https://github.com/ScoopInstaller/Extras/issues/9654

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rasa** [comment]
```batch
--> Installing the Manifest devtoys-np.json

Installing 'devtoys-np' (1.0.10.0) [64bit]
64360VelerSoftware.DevToys_1.0.10.0_neutral_._j80j2txgjg9dj.msixbundle (157.6 MB) [===============================] 100%
Checking hash of 64360VelerSoftware.DevToys_1.0.10.0_neutral_._j80j2txgjg9dj.msixbundle ... ok.
Running pre_install script...
Linking ~\scoop\apps\devtoys-np\current => ~\scoop\apps\devtoys-np\1.0.10.0
'devtoys-np' (1.0.10.0) was installed successfully!

--> Refreshing environment variables

--> Comparing ARP Entries

PS C:\Users\WDAGUtilityAccount\Desktop\bucket> scoop uninstall devtoys-np
Uninstalling 'devtoys-np' (1.0.10.0).
Running pre_uninstall script...
Remove-Item : Cannot find path 'C:\ProgramData\Packages\64360VelerSoftware.DevToys_j80j2txgjg9dj' because it does not
exist.
At line:2 char:1
+ Remove-Item "$env:ProgramData\Packages\64360VelerSoftware.DevToys_j80 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\ProgramData\...s_j80j2txgjg9dj:String) [Remove-Item], ItemNotFoundExcept
   ion
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Unlinking ~\scoop\apps\devtoys-np\current
'devtoys-np' was uninstalled.
PS C:\Users\WDAGUtilityAccount\Desktop\bucket>
```

**Comment by Zliced13** [comment]
@rasa Test it again, it should work this time.

**Comment by rasa** [comment]
```batch
--> Running: scoop install  devtoys-np.json

Installing 'devtoys-np' (1.0.10.0) [64bit]
64360VelerSoftware.DevToys_1.0.10.0_neutral_._j80j2txgjg9dj.msixbundle (157.6 MB) [===============================] 100%
Checking hash of 64360VelerSoftware.DevToys_1.0.10.0_neutral_._j80j2txgjg9dj.msixbundle ... ok.
Running pre_install script...
Linking ~\scoop\apps\devtoys-np\current => ~\scoop\apps\devtoys-np\1.0.10.0
'devtoys-np' (1.0.10.0) was installed successfully!

--> Refreshing environment variables

--> Comparing ARP entries

PS C:\Users\WDAGUtilityAccount\Desktop\bucket> scoop list
Installed apps:

Name       Version          Source                                                          Updated             Info
----       -------          ------                                                          -------             ----
7zip       22.01            main                                                            2023-01-21 08:23:17
dark       3.11.2           main                                                            2023-01-21 08:23:25
devtoys-np 1.0.10.0         C:\Users\WDAGUtilityAccount\Desktop\SandboxTest\devtoys-np.json 2023-01-21 08:23:49
git        2.39.1.windows.1 main                                                            2023-01-21 08:23:24
innounp    0.50             main                                                            2023-01-21 08:23:25
lessmsi    1.10.0           main                                                            2023-01-21 08:23:25


PS C:\Users\WDAGUtilityAccount\Desktop\bucket> scoop uninstall devtoys-np
Uninstalling 'devtoys-np' (1.0.10.0).
Running pre_uninstall script...
Unlinking ~\scoop\apps\devtoys-np\current
'devtoys-np' was uninstalled.
PS C:\Users\WDAGUtilityAccount\Desktop\bucket>
```

**Pull request merged**
