### PR TITLE
translucenttb-np: Add version 2022.1

### PR DESCRIPTION
**Pull request by Zliced13**
Closes https://github.com/ScoopInstaller/Extras/issues/10071

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rasa** [comment]
@Zliced13 Uninstall failed:
```batch
--> Installing the Manifest translucenttb-np.json

Installing 'translucenttb-np' (2022.1) [64bit]
bundle.msixbundle (6.5 MB) [======================================================================================] 100%
Checking hash of bundle.msixbundle ... ok.
Running pre_install script...
Linking ~\scoop\apps\translucenttb-np\current => ~\scoop\apps\translucenttb-np\2022.1
'translucenttb-np' (2022.1) was installed successfully!

--> Refreshing environment variables

--> Comparing ARP Entries

PS C:\Users\WDAGUtilityAccount\Desktop\bucket> scoop uninstall translucenttb-np
Uninstalling 'translucenttb-np' (2022.1).
Running pre_uninstall script...
Remove-Item : Cannot find path 'C:\ProgramData\Packages' because it does not exist.
At line:2 char:1
+ Remove-Item "$env:ProgramData\Packages\*.TranslucentTB_*" -Force -Rec ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\ProgramData\Packages:String) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Unlinking ~\scoop\apps\translucenttb-np\current
'translucenttb-np' was uninstalled.
PS C:\Users\WDAGUtilityAccount\Desktop\bucket>
```

**Comment by Zliced13** [comment]
@rasa Test it again, it should work this time.

**Comment by rasa** [comment]
Installed and uninstalled fine.

**Pull request merged**
