### PR TITLE
mullvadvpn-np: Add version 2022.5

### PR DESCRIPTION
**Pull request by Zliced13**
Closes https://github.com/ScoopInstaller/Extras/issues/7113

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rasa** [comment]
Never finished installing:
```batch
--> Installing the Manifest mullvadvpn-np.json

Installing 'mullvadvpn-np' (2022.5) [64bit]
MullvadVPN-2022.5.exe (83.0 MB) [=================================================================================] 100%
Checking hash of MullvadVPN-2022.5.exe ... ok.
Running pre_install script...
```
2023-01-19_17-58-16-WindowsSandboxClient-Windows_Sandbox

**Comment by Zliced13** [comment]
@rasa I fixed it, try again now and tell me your results please.

**Comment by rasa** [comment]
```batch
--> Running: scoop install  mullvadvpn-np.json

Installing 'mullvadvpn-np' (2022.5) [64bit]
MullvadVPN-2022.5.exe (83.0 MB) [=================================================================================] 100%
Checking hash of MullvadVPN-2022.5.exe ... ok.
Running pre_install script...
Linking ~\scoop\apps\mullvadvpn-np\current => ~\scoop\apps\mullvadvpn-np\2022.5
'mullvadvpn-np' (2022.5) was installed successfully!

--> Refreshing environment variables

--> Comparing ARP entries

DisplayName          DisplayVersion Publisher   ProductCode
-----------          -------------- ---------   -----------
Mullvad VPN 2022.5.0 2022.5.0       Mullvad VPN 2A356FD4-03B7-4F45-99B4-737BE580DC82



PS C:\Users\WDAGUtilityAccount\Desktop\bucket> scoop uninstall mullvadvpn-np
Uninstalling 'mullvadvpn-np' (2022.5).
Running pre_uninstall script...
Unlinking ~\scoop\apps\mullvadvpn-np\current
'mullvadvpn-np' was uninstalled.
PS C:\Users\WDAGUtilityAccount\Desktop\bucket>
```

**Pull request merged**
