### PR TITLE
hp-support-assistant-np: Add version 9.20.22.0.142501-143000.142943

### LINKED ISSUE #108: [Request] HP Support Assistant
### Criteria

For a package to be acceptable in the Nonportable bucket, it should be:

- [x] a reasonably well-known and widely used application
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version

### Information

**Name:** HP Support Assistant
I
**Description:** HP Support Assistant is a one-stop solution for connected, contextual support. Aided with a new user interface and other usability enhancements, HP Support Assistant helps you maintain your HP devices— enabling you to prevent or resolve problems by using automated updates and self-help options. What’s more, HP Support Assistant guides you to expert support when you need it.

**Homepage:** https://support.hp.com/us-en/help/hp-support-assistant

**Download link(s):** https://ftp.ext.hp.com/pub/softpaq/sp142501-143000/sp142943.exe

**Some indication of popularity/repute:** 

It is installed on more or less on every HP laptop and HP  PCs.

Don't know where to look for "Repute"

For more info:

Some more info: http://h10032.www1.hp.com/ctg/Manual/c06593496.pdf

Opening this issue in favour of [this one](https://github.com/ScoopInstaller/Extras/issues/9912)

### PR DESCRIPTION
**Pull request by Zliced13**
Closes #108

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rasa** [comment]
```batch
--> Installing the Manifest hp-support-assistant-np.json

Installing 'hp-support-assistant-np' (9.20.22.0.142501-143000.142943) [64bit]
sp142943.exe (165.8 MB) [=========================================================================================] 100%
Checking hash of sp142943.exe ... ok.
Linking ~\scoop\apps\hp-support-assistant-np\current => ~\scoop\apps\hp-support-assistant-np\9.20.22.0.142501-143000.142943
Running post_install script...
'hp-support-assistant-np' (9.20.22.0.142501-143000.142943) was installed successfully!

--> Refreshing environment variables

--> Comparing ARP Entries

PS C:\Users\WDAGUtilityAccount\Desktop\bucket> scoop uninstall hp-support-assistant-np
Uninstalling 'hp-support-assistant-np' (9.20.22.0.142501-143000.142943).
Running pre_uninstall script...
Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
At line:2 char:1
+ Start-Process "$dir\UninstallHPSA.exe" -Wait -Verb 'RunAs' -ArgumentL ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

Unlinking ~\scoop\apps\hp-support-assistant-np\current
'hp-support-assistant-np' was uninstalled.
PS C:\Users\WDAGUtilityAccount\Desktop\bucket>
```

**Comment by rasa** [comment]
Uninstall fails. See above.

**Comment by Zliced13** [comment]
@anderlli0053, Do you have an HP laptop/desktop computer? If yes, can you please test this manifest in my personal bucket? And give me feedback if it's working properly, or not working properly?

```
scoop bucket add MyScoop 'https://github.com/Zliced13/MyScoop'
```
```
scoop install hp-support-assistant-np
```

**Comment by Zliced13** [comment]
I think this software is meant to only work with HP laptop/desktop computers.

**Comment by anderlli0053** [comment]
> @anderlli0053, Do you have an HP laptop/desktop computer? If yes, can you please test this manifest in my personal bucket? And give me feedback if it's working properly, or not working properly?
> 
> ```
> scoop bucket add MyScoop 'https://github.com/Zliced13/MyScoop'
> ```
> 
> ```
> scoop install hp-support-assistant-np
> ```

Yes, i have **HP Pavilion Gaming Laptop 15-ec0xxx**


I'll test it now

**Comment by anderlli0053** [comment]
@Zliced13 



```
PS C:\Windows\System32> scoop update && scoop install MyScoop/hp-support-assistant-np
Updating Scoop...
Updating Buckets...
Scoop was updated successfully!
WARN  'hp-support-assistant-np' (9.20.22.0.142501-143000.142943) is already installed.
Use 'scoop update hp-support-assistant-np' to install a new version.
```

**Comment by anderlli0053** [comment]
@Zliced13 I'm force reinstalling it right now, hang on..

**Comment by anderlli0053** [comment]
@Zliced13 


```
PS C:\Windows\System32> scoop install MyScoop/hp-support-assistant-np
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'hp-support-assistant-np' (9.20.22.0.142501-143000.142943) [64bit] from MyScoop bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 2b4c17|OK  |   1.4MiB/s|C:/Users/ander/scoop/cache/hp-support-assistant-np#9.20.22.0.142501-143000.142943#https_ftp.ext.hp.com_pub_softpaq_sp142501-143000_sp142943.exe_installer.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of sp142943.exe ... ok.
Linking ~\scoop\apps\hp-support-assistant-np\current => ~\scoop\apps\hp-support-assistant-np\9.20.22.0.142501-143000.142943
Running post_install script...
'hp-support-assistant-np' (9.20.22.0.142501-143000.142943) was installed successfully!
PS C:\Windows\System32>
```


It installs without any problem, after the install it pops up the message that the "Installation is complete"

also it is listed in Start Menu:




It correctly detects and lists the laptop:

**Comment by Zliced13** [comment]
@rasa Is this good enough for you?

**Comment by Zliced13** [comment]
Thank you for testing @anderlli0053.

**Comment by anderlli0053** [comment]
@Zliced13  No problem at all.

**Pull request merged**
