### PR TITLE
protonvpn-np: fix install & uninstall scripts

### LINKED ISSUE #119: protonvpn-np Errors in installing and uninstalling
## Bug Report

**Package Name:** protonvpn-np

### Current Behaviour

PS C:\Users\siyu> gsudo scoop install protonvpn-np
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'protonvpn-np' (2.3.1) [64bit] from nonportable bucket
Loading ProtonVPN_win_v2.3.1.exe from cache.
Checking hash of ProtonVPN_win_v2.3.1.exe ... ok.
Running installer script...
Remove-Item : Cannot find path 'C:\Users\Public\Desktop\ProtonVPN.lnk' because it does not exist.
At line:4 char:1
+ Remove-Item "$Env:Public\Desktop\ProtonVPN.lnk"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Public\Desktop\ProtonVPN.lnk:String) [Remove-Item], I
   temNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Linking ~\scoop\apps\protonvpn-np\current => ~\scoop\apps\protonvpn-np\2.3.1
'protonvpn-np' (2.3.1) was installed successfully!

PS C:\Users\siyu> gsudo scoop uninstall protonvpn-np
Uninstalling 'protonvpn-np' (2.3.1).
Running uninstaller script...
### **ERROR Exit code was 1605!**
Unlinking ~\scoop\apps\protonvpn-np\current
'protonvpn-np' was uninstalled.

### System details

**Windows version:** 10

**OS architecture:**  64bit

**PowerShell version:** 5.1.19041.2364

### PR DESCRIPTION
**Pull request by StarsbySea**
Closes #119 

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Zliced13** [comment]
@StarsbySea do you mind closing your PR? My PR will update `protonvpn-np` to the latest version, which is 3.0.5.

**Comment by StarsbySea** [comment]
New PR #204

**Comment by Zliced13** [comment]
Also, thank you for your contribution of the `duckduckgo-browser` manifest.

**Pull request closed without merging**
