### PR TITLE
protonvpn-np: Updated the manifest.

### PR DESCRIPTION
**Pull request by Zliced13**
Updated the `URL`, `hash`, added `architecture`, updated the `pre_install` & `pre_uninstall` scripts, and updated `license`.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Zliced13** [comment]
@HUMORCE I hope I am not asking for much, but could you please merge this PR? It's a very important and significant change to the `protonvpn-np` manifest.

**Review by HUMORCE — APPROVED** [review]
Tested in VM.

**Comment by Zliced13** [comment]
Thank you, @HUMORCE, have a great day.

**Pull request merged**
