### PR TITLE
spotx-np: updating parameters

### PR DESCRIPTION
**Pull request by amd64fox**

### CODE REVIEW

**Comment by Ast3risk-ops** [comment]
merge plz

**Comment by drewbitt** [comment]
PR merges happen about once a month so let's hope this is merged soon.

**Comment by x0rzavi** [comment]
Why isn't the PR getting merged yet?

**Comment by amd64fox** [comment]
idk
@rasa merge this please

**Comment by Ast3risk-ops** [comment]
I have incorporated this fix into https://github.com/Ast3risk-ops/spotx-bucket.

**Pull request closed without merging**
