### PR TITLE
freelan-np: Add version 2.2.0

### PR DESCRIPTION
**Pull request by Zliced13**
Closes https://github.com/ScoopInstaller/Extras/issues/10319

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rasa** [comment]
Got stuck:
2023-01-31_21-38-36-WindowsSandboxClient-Windows_Sandbox

**Comment by Zliced13** [comment]
> Got stuck:
> 
> 2023-01-31_21-38-36-WindowsSandboxClient-Windows_Sandbox
> 
> 

Did you not get a prompt asking you to install the **free lan driver**?

**Comment by rasa** [comment]
> Did you not get a prompt asking you to install the **free lan driver**?

No, just a blank window, sorry.

**Comment by Zliced13** [comment]
@rasa, have you tried doing it on a Windows vm (ex. Oracle Virtual Box) instead of using a Windows sandbox?

**Comment by rasa** [comment]
> @rasa, have you tried doing it on a Windows VM (ex. an Oracle Virtual Box VM) instead of using a Windows sandbox?

No, but that's a good idea. I had a script to quickly spin up a VM via Vagrant, but it's wired to a specific project, and would need to be rewritten.

**Comment by Zliced13** [comment]
Let me know how it gos for you once you set it up.

**Pull request merged**
