### PR TITLE
proton-mail-bridge-np: Add version 2.1.3

### PR DESCRIPTION
**Pull request by nagromc**
Closes ScoopInstaller/Extras#7139

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by issaclin32** [comment]
Thanks for the PR, but it seems that this app can be installed in the portable way.
The installer is made with *AdvancedInstaller*, and can be extracted using `/extract:(TARGET)` command.

I just made a PR in *Extras* (https://github.com/ScoopInstaller/Extras/pull/8702), would you like to help test the package?

**Comment by rashil2000** [comment]
Added in Extras

**Comment by nagromc** [comment]
> Thanks for the PR, but it seems that this app can be installed in the portable way. The installer is made with _AdvancedInstaller_, and can be extracted using `/extract:(TARGET)` command.
> 
> I just made a PR in _Extras_ ([ScoopInstaller/Extras#8702](https://github.com/ScoopInstaller/Extras/pull/8702)), would you like to help test the package?

Everything works as expected. Thanks.

**Pull request closed without merging**
