### PR TITLE
veracrypt-np: Add version 1.26.7

### PR DESCRIPTION
**Pull request by FlawlessCasual17**
Closes https://github.com/ScoopInstaller/Extras/issues/2381
Closes https://github.com/ScoopInstaller/Extras/issues/10728

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Gabriel-Graf** [comment]
Thank you for mentioning this PR, @aliesbelik.

@FlawlessCasual17, I tested your manifest, and it works for me like a charm. However, as of now, there is already version 1.26.7 available. Scoop installs only version 1.25.9, and `scoop update` doesn't seem to have an effect. Am I using Scoop incorrectly in this case?

**Comment by FlawlessCasual17** [comment]
@Gabriel-Graf I changed it

**Comment by Gabriel-Graf** [comment]
may i ask why this PR is not added to main?

**Comment by FlawlessCasual17** [comment]
> may i ask why this PR is not added to main?

You mean the [**Main**](https://github.com/ScoopInstaller/Main) bucket?

**Comment by Gabriel-Graf** [comment]
sorry for the confusion. i meant why is this PR not merged because i would like to install veracrypt with scoop and the extra bucket-repo.

**Comment by FlawlessCasual17** [comment]
> sorry for the confusion. i meant why is this PR not merged because i would like to install veracrypt with scoop and the extra bucket-repo.

Sorry, but you are going to have to wait, as I am doing already, until somebody with admin privileges wants to merge my Pull Request.

**Pull request closed without merging**
