### PR TITLE
SpotX-np: Changing the repository link

### PR DESCRIPTION
**Pull request by amd64fox**
https://github.com/SpotX-CLI/SpotX-Win/issues/54
Since the repository link changed, it caused an incorrect version error.
Please check if everything is ok now

### CODE REVIEW

**Comment by amd64fox** [comment]
merge? @issaclin32

**Comment by Lutra-Fs** [comment]
@rashil2000 seems like Issac Lin is not here for several days and this fix needs to be applied asap so I wonder if it is okay to notify you to merge this request. I found that in my local machine the checkver script will simply exit after the error. However, in GitHub action, the update process will continue to run. Thank you.
>```powershell
>ERROR Could match '(?sm)Commits on ([\w\s,]+)</h2>.*?SpotX/commits/([0-9a-f]{6})' on >'https://github.com/amd64fox/SpotX/commits/main/Install.ps1'
>MethodInvocationException: C:\Users\runneradmin\SCOOP\apps\scoop\current\bin\checkver.ps1:338
>Line |
> 338 |  …               $match = $regex.Matches($page) | Select-Object -First 1
>     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     | Exception calling "Matches" with "1" argument(s): "Value cannot be null. (Parameter 'input')"
>
>spotx-np: 6.2.1 (scoop version is 2019.1-beta6) autoupdate available
>Autoupdating spotx-np
>Downloading Install.ps1 to compute hashes!
>```

while in my local machine
```powershell
ERROR Could match '(?sm)Commits on ([\w\s,]+)</h2>.*?SpotX/commits/([0-9a-f]{6})' on 'https://github.com/amd64fox/SpotX/commits/main/Install.ps1'
Exception calling "Matches" with "1" argument(s): "Value cannot be null.
Parameter name: input"
At C:\Users\lutra\scoop\apps\scoop\current\bin\checkver.ps1:343 char:17
+ ...               $match = $regex.Matches($page) | Select-Object -First 1
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException
```

**Comment by rashil2000** [comment]
Could you fix the conflicts?

**Comment by amd64fox** [comment]
@rashil2000 
fixed conflict

**Pull request merged**
